version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apoia_db
      MYSQL_USER: apoia_user
      MYSQL_PASSWORD: apoia_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data:
