spring:
  application:
    name: Apo.IA
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: apo_ia
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3

jwt:
  secret: ${JWT_SECRET:OhanaQuerDizerFamiliaFamiliaQuerDizerNuncaAbandonarOuEsquecer}
