spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/apoia-test

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
