spring:
  application:
    name: Apo.IA
  datasource:
    url: jdbc:mysql://apoia-server.mysql.database.azure.com:3306/apoia-database?sslMode=REQUIRED
    username: cfcgslijye@apoia-server
    password: KiwiRosa@2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
server:
  servlet:
    context-path: /


jwt:
  secret: ${JWT_SECRET:OhanaQuerDizerFamiliaFamiliaQuerDizerNuncaAbandonarOuEsquecer}
