spring:
  application:
    name: Apo.IA
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553791
    password: 180298
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.OracleDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: apo_ia
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
server:
  servlet:
    context-path: /


jwt:
  secret: ${JWT_SECRET:OhanaQuerDizerFamiliaFamiliaQuerDizerNuncaAbandonarOuEsquecer}
