spring:
  application:
    name: Apo.IA
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: apo_ia
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
server:
  servlet:
    context-path: /


jwt:
  secret: ${JWT_SECRET:OhanaQuerDizerFamiliaFamiliaQuerDizerNuncaAbandonarOuEsquecer}
